<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-A3I7V83" failures="1" tests="2" name="Test" time="0.311" errors="0" timestamp="2023-07-25T20:21:30 IST">
  <testcase classname="intro.Test2" name="goToTheLink" time="0.031"/>
  <testcase classname="intro.Test2" name="login" time="0.099">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at intro.Test2.login(Test2.java:19)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- login -->
</testsuite> <!-- Test -->
